# Generated by Django 4.0.10 on 2024-03-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainParser', '0016_rename_nocall_ad_no_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('test_phone', models.CharField(max_length=20, verbose_name='Тестовый номер')),
            ],
        ),
        migrations.CreateModel(
            name='TestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата звонка')),
                ('date_done', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainParser.profile', verbose_name='Пользователь')),
                ('phone_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvonilka_test_phones.phonetest', verbose_name='Тест')),
            ],
        ),
    ]
