# Generated by Django 4.0.10 on 2024-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonilka_test_phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonetest',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='testcall',
            name='person',
        ),
        migrations.AddField(
            model_name='testcall',
            name='person_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcall',
            name='person_phone',
            field=models.CharField(default='test', max_length=255, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
