# Generated by Django 4.0.3 on 2022-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('site', models.CharField(choices=[('ci', 'Cian'), ('av', 'Avito')], max_length=2)),
                ('address', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('person', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
