# Generated by Django 4.0.3 on 2022-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
