# Generated by Django 4.0.3 on 2022-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tmpDone',
            field=models.BooleanField(default=False),
        ),
    ]
