# Generated by Django 4.0.3 on 2022-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0004_ad_tmpdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='person',
            field=models.CharField(default='', max_length=30),
        ),
    ]
