# Generated by Django 4.0.3 on 2022-04-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0007_alter_ad_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
