# Generated by Django 4.0.3 on 2022-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0009_ad_frontdone_ad_nocall_profile_working_targetad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='focused',
            field=models.BooleanField(default=False),
        ),
    ]
