# Generated by Django 4.0.7 on 2022-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0010_ad_focused'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clearColor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
