# Generated by Django 4.0.7 on 2022-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0011_ad_clearcolor_ad_views_alter_ad_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
