# Generated by Django 4.0.7 on 2022-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0012_alter_ad_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='full_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
