# Generated by Django 4.0.7 on 2022-12-11 16:19

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainParser', '0013_ad_full_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date_done',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_first',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='person',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
