# Generated by Django 4.0.10 on 2024-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainParser', '0016_rename_nocall_ad_no_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='calls_amount',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Приоритетный?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working',
            field=models.BooleanField(default=True, verbose_name='Работает?'),
        ),
    ]
